In [1]:
import pandas as pd

# Read the file with semicolon delimiter
df = pd.read_csv('LVTripAdvisor.csv', sep=';')

# Save as CSV file
df.to_csv('BetterLVTripAdvisor.csv', index=False)

We will be using SVC (Support Vector Classifier) from the Scikit-learn library to implement this model and evaluating the predictions using a classification report and a confusion matrix. We will later optimize the model using grid search.

In [2]:
##import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix
df = pd.read_csv('BetterLVTripAdvisor.csv') #read the csv
df

,User country,Nr. reviews,Nr. hotel reviews,Helpful votes,Score,Period of stay,Traveler type,Pool,Gym,Tennis court,Spa,Casino,Free internet,Hotel name,Hotel stars,Nr. rooms,User continent,Member years,Review month,Review weekday
0,USA,11,4,13,5,Dec-Feb,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,January,Thursday
1,USA,119,21,75,3,Dec-Feb,Business,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,3,January,Friday
2,USA,36,9,25,5,Mar-May,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,February,Saturday
3,UK,14,7,14,4,Mar-May,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,6,February,Friday
4,Canada,5,5,2,4,Mar-May,Solo,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,7,March,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,UK,15,4,8,5,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,Europe,1,October,Sunday
500,Canada,50,13,29,4,Sep-Nov,Couples,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,8,November,Thursday
501,USA,154,23,31,4,Sep-Nov,Friends,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,4,November,Thursday
502,USA,9,6,5,2,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,9,December,Wednesday
503,USA,20,19,112,4,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,The Westin las Vegas Hotel Casino & Spa,4,826,North America,5,December,Tuesday

In [3]:



from sklearn.preprocessing import LabelEncoder

# Define a list of features you want to encode
features_to_encode = ['Hotel stars','Period of stay', 'Traveler type','Pool','Gym','Tennis court','Spa','Casino','Free internet','Hotel name','User continent','User country','Review month','Review weekday']

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Encode each feature in the DataFrame
for feature in features_to_encode:
    df[feature] = (label_encoder.fit_transform(df[feature]))
df
# If you want to transform new data using the same encoder,
##Set x and y variables

,User country,Nr. reviews,Nr. hotel reviews,Helpful votes,Score,Period of stay,Traveler type,Pool,Gym,Tennis court,Spa,Casino,Free internet,Hotel name,Hotel stars,Nr. rooms,User continent,Member years,Review month,Review weekday
0,46,11,4,13,5,0,3,0,1,0,0,1,1,2,0,3773,3,9,4,4
1,46,119,21,75,3,0,0,0,1,0,0,1,1,2,0,3773,3,3,4,0
2,46,36,9,25,5,2,2,0,1,0,0,1,1,2,0,3773,3,2,3,2
3,45,14,7,14,4,2,3,0,1,0,0,1,1,2,0,3773,2,6,3,0
4,3,5,5,2,4,2,4,0,1,0,0,1,1,2,0,3773,3,7,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,45,15,4,8,5,3,1,1,1,0,1,1,1,14,2,826,2,1,10,3
500,3,50,13,29,4,3,1,1,1,0,1,1,1,14,2,826,3,8,9,4
501,46,154,23,31,4,3,3,1,1,0,1,1,1,14,2,826,3,4,9,4
502,46,9,6,5,2,0,2,1,1,0,1,1,1,14,2,826,3,9,2,6
503,46,20,19,112,4,0,2,1,1,0,1,1,1,14,2,826,3,5,2,5

In [4]:
x=df.drop('Score', axis=1)
y=df['Score']

##Split the data into training and test tests
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.4, random_state=15)

##set algorithm
gbm = GradientBoostingClassifier(n_estimators=100, learning_rate=.1, max_depth=3, random_state=15)
gbm.fit(x_train, y_train)
##fit the algorith to the training data

#assign a new variable to the prediction of the x test data
model_predict=gbm.predict(x_test)

#confusion matrix
print(confusion_matrix(y_test, model_predict))

#classification report
print(classification_report(y_test, model_predict))

[[ 1  1  1  1  2]
 [ 0  1  1  2  8]
 [ 0  2  3 16 14]
 [ 0  1  3 29 31]
 [ 1  0  2 25 57]]
              precision    recall  f1-score   support

           1       0.50      0.17      0.25         6
           2       0.20      0.08      0.12        12
           3       0.30      0.09      0.13        35
           4       0.40      0.45      0.42        64
           5       0.51      0.67      0.58        85

    accuracy                           0.45       202
   macro avg       0.38      0.29      0.30       202
weighted avg       0.42      0.45      0.42       202

In [5]:
import pandas as pd

# Assuming gbm is your trained model and x_test is your test data
Predictions = gbm.predict(x_test)

# Create a DataFrame for new data with an explicit index
new_data = pd.DataFrame({
    "User country": [1],
    "Nr. reviews": [100],
    "Nr. hotel reviews": [20],
    "Helpful votes": [10],
    "Period of stay": [2],
    "Traveler type": [4],
    "Pool": [1],
    "Gym": [2],
    "Tennis court": [1],
    "Spa": [1],
    "Casino": [2],
    "Free internet": [2],
    "Hotel name": [15],
    "Hotel stars": [3],
    "Nr. rooms": [826],
    "User continent": [4],
    "Member years": [2],
    "Review month": [10],
    "Review weekday": [4]
}, index=[0])  # Specify index as [0] for a single row DataFrame

# Predict for new data
new_predictions = gbm.predict(new_data)

print("Predicting score for new review:", new_predictions)

Predicting score for new review: [5]

The report above can be observed to predict the factors which relate to a positive or negative hotel review, Importantly we can normalize across the value of reviews based on times of the year, there by making the overall prediction model more robust, as in on times of the year, like holidays reviews may be in a better or worse state due to holiday cheer, or busy times creating unique problems. This data can be used to determine what components of a hotel in las vegas result in higher degrees of customer satisfaction, such as ammenities like casinos, pools, spas, and tennis courts, while alos considering the general star rating of the hotel. like a 1 star hotel getting a review of 4, may be considered a positive outcome, but a 3 star hotel may not consider a score of 4 to be successful. It can be observed from the above matrix that this data is somewhat significant but due to the total pool of reviews being limited, (only about 600 records) it limits the accuracy especially when scoring across 5 point systems. an alternative future study may split reviews of 4 and higher as a 'positive' review, and 3 and below as a negative review, which would y